name: tutorial

channels:
    - defaults
    - conda-forge
    - anaconda

dependencies:
    - python=3.7.5
    - scikit-learn=0.22.1
    - fbprophet=0.6
    - numpy=1.19.1
    - pandas=1.1.1
    - pip
    - pip:
      - mlflow >= 1.0